export const blogPosts = [
  {
    id: 1,
    title: "Getting Started with Next.js 15",
    excerpt: "Learn the basics of Next.js and how to build your first modern web application with server-side rendering.",
    category: "Technology",
    date: "March 15, 2024",
    readTime: "8 min read",
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 2,
    title: "E-commerce Design Best Practices",
    excerpt: "Discover essential design principles for creating user-friendly e-commerce platforms that convert visitors into customers.",
    category: "Design",
    date: "March 12, 2024",
    readTime: "6 min read",
    image: "https://images.pexels.com/photos/3962286/pexels-photo-3962286.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 3,
    title: "Tailwind CSS Tips and Tricks",
    excerpt: "Master CSS-in-the-markup with Tailwind. Learn advanced techniques to speed up your development workflow.",
    category: "Development",
    date: "March 10, 2024",
    readTime: "7 min read",
    image: "https://images.pexels.com/photos/3962286/pexels-photo-3962286.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 4,
    title: "Understanding React Hooks",
    excerpt: "Deep dive into React Hooks and learn how to manage state and side effects in functional components.",
    category: "Technology",
    date: "March 8, 2024",
    readTime: "10 min read",
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 5,
    title: "Building Accessible Web Applications",
    excerpt: "Create inclusive digital experiences by implementing accessibility best practices in your web projects.",
    category: "Accessibility",
    date: "March 5, 2024",
    readTime: "9 min read",
    image: "https://images.pexels.com/photos/3962286/pexels-photo-3962286.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 6,
    title: "Performance Optimization Strategies",
    excerpt: "Boost your website performance with proven optimization techniques and tools.",
    category: "Development",
    date: "March 1, 2024",
    readTime: "11 min read",
    image: "https://images.pexels.com/photos/3962286/pexels-photo-3962286.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 7,
    title: "Web Design Trends 2024",
    excerpt: "Explore the latest design trends that are shaping the future of web and digital experiences.",
    category: "Design",
    date: "February 28, 2024",
    readTime: "5 min read",
    image: "https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 8,
    title: "SEO Secrets for E-commerce",
    excerpt: "Optimize your online store for search engines and drive organic traffic to boost sales.",
    category: "Marketing",
    date: "February 25, 2024",
    readTime: "8 min read",
    image: "https://images.pexels.com/photos/3962286/pexels-photo-3962286.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
]