export interface Category {
  id: number;
  name: string;
  slug: string;
  parentId: number | null;
  children: Category[];
}

const navItems: Category[] = [

  // ==========================================
  // 1. ELECTRONICS
  // ==========================================
  {
    id: 1,
    name: "Electronics",
    slug: "electronics",
    parentId: null,
    children: [
      {
        id: 101,
        name: "Smartphones",
        slug: "smartphones",
        parentId: 1,
        children: [
          { id: 1011, name: "Apple iPhone",       slug: "apple-iphone",       parentId: 101, children: [] },
          { id: 1012, name: "Samsung Galaxy",      slug: "samsung-galaxy",      parentId: 101, children: [] },
          { id: 1013, name: "Google Pixel",        slug: "google-pixel",        parentId: 101, children: [] },
          { id: 1014, name: "OnePlus",             slug: "oneplus",             parentId: 101, children: [] },
          { id: 1015, name: "Xiaomi",              slug: "xiaomi",              parentId: 101, children: [] },
          { id: 1016, name: "Motorola",            slug: "motorola",            parentId: 101, children: [] },
          { id: 1017, name: "Sony Xperia",         slug: "sony-xperia",         parentId: 101, children: [] },
          { id: 1018, name: "Asus ROG Phone",      slug: "asus-rog-phone",      parentId: 101, children: [] },
          { id: 1019, name: "Nothing Phone",       slug: "nothing-phone",       parentId: 101, children: [] },
          { id: 1020, name: "Refurbished Phones",  slug: "refurbished-phones",  parentId: 101, children: [] },
        ],
      },
      {
        id: 102,
        name: "Laptops & Computers",
        slug: "laptops-computers",
        parentId: 1,
        children: [
          { id: 1021, name: "Gaming Laptops",      slug: "gaming-laptops",      parentId: 102, children: [] },
          { id: 1022, name: "MacBooks",            slug: "macbooks",            parentId: 102, children: [] },
          { id: 1023, name: "Ultrabooks",          slug: "ultrabooks",          parentId: 102, children: [] },
          { id: 1024, name: "Chromebooks",         slug: "chromebooks",         parentId: 102, children: [] },
          { id: 1025, name: "Desktop PCs",         slug: "desktop-pcs",         parentId: 102, children: [] },
          { id: 1026, name: "Workstations",        slug: "workstations",        parentId: 102, children: [] },
          { id: 1027, name: "2-in-1 Laptops",      slug: "2-in-1-laptops",      parentId: 102, children: [] },
          { id: 1028, name: "Mini PCs",            slug: "mini-pcs",            parentId: 102, children: [] },
          { id: 1029, name: "All-in-One PCs",      slug: "all-in-one-pcs",      parentId: 102, children: [] },
          { id: 1030, name: "Refurbished Laptops", slug: "refurbished-laptops", parentId: 102, children: [] },
        ],
      },
      {
        id: 103,
        name: "Audio & Headphones",
        slug: "audio-headphones",
        parentId: 1,
        children: [
          { id: 1031, name: "Wireless Earbuds",           slug: "wireless-earbuds",           parentId: 103, children: [] },
          { id: 1032, name: "Over-Ear Headphones",        slug: "over-ear-headphones",        parentId: 103, children: [] },
          { id: 1033, name: "Soundbars",                  slug: "soundbars",                  parentId: 103, children: [] },
          { id: 1034, name: "Bluetooth Speakers",         slug: "bluetooth-speakers",         parentId: 103, children: [] },
          { id: 1035, name: "Studio Monitors",            slug: "studio-monitors",            parentId: 103, children: [] },
          { id: 1036, name: "Noise-Cancelling Headphones",slug: "noise-cancelling-headphones",parentId: 103, children: [] },
          { id: 1037, name: "Gaming Headsets",            slug: "gaming-headsets",            parentId: 103, children: [] },
          { id: 1038, name: "Portable Speakers",          slug: "portable-speakers",          parentId: 103, children: [] },
          { id: 1039, name: "Home Theater Systems",       slug: "home-theater-systems",       parentId: 103, children: [] },
          { id: 1040, name: "Turntables",                 slug: "turntables",                 parentId: 103, children: [] },
        ],
      },
      {
        id: 104,
        name: "Wearable Technology",
        slug: "wearable-technology",
        parentId: 1,
        children: [
          { id: 1041, name: "Smartwatches",          slug: "smartwatches",          parentId: 104, children: [] },
          { id: 1042, name: "Fitness Trackers",      slug: "fitness-trackers",      parentId: 104, children: [] },
          { id: 1043, name: "Smart Rings",           slug: "smart-rings",           parentId: 104, children: [] },
          { id: 1044, name: "VR Headsets",           slug: "vr-headsets",           parentId: 104, children: [] },
          { id: 1045, name: "Smart Glasses",         slug: "smart-glasses",         parentId: 104, children: [] },
          { id: 1046, name: "GPS Watches",           slug: "gps-watches",           parentId: 104, children: [] },
          { id: 1047, name: "Health Monitors",       slug: "health-monitors",       parentId: 104, children: [] },
          { id: 1048, name: "Smart Clothing",        slug: "smart-clothing",        parentId: 104, children: [] },
          { id: 1049, name: "Kids' Smartwatches",    slug: "kids-smartwatches",     parentId: 104, children: [] },
          { id: 1050, name: "Refurbished Wearables", slug: "refurbished-wearables", parentId: 104, children: [] },
        ],
      },
      {
        id: 105,
        name: "Cameras & Photography",
        slug: "cameras-photography",
        parentId: 1,
        children: [
          { id: 1051, name: "DSLR Cameras",       slug: "dslr-cameras",       parentId: 105, children: [] },
          { id: 1052, name: "Mirrorless Cameras", slug: "mirrorless-cameras", parentId: 105, children: [] },
          { id: 1053, name: "Action Cameras",     slug: "action-cameras",     parentId: 105, children: [] },
          { id: 1054, name: "Drone Cameras",      slug: "drone-cameras",      parentId: 105, children: [] },
          { id: 1055, name: "Instant Cameras",    slug: "instant-cameras",    parentId: 105, children: [] },
          { id: 1056, name: "Security Cameras",   slug: "security-cameras",   parentId: 105, children: [] },
          { id: 1057, name: "Camera Lenses",      slug: "camera-lenses",      parentId: 105, children: [] },
          { id: 1058, name: "Tripods & Stands",   slug: "tripods-stands",     parentId: 105, children: [] },
          { id: 1059, name: "Underwater Cameras", slug: "underwater-cameras", parentId: 105, children: [] },
          { id: 1060, name: "Film Cameras",       slug: "film-cameras",       parentId: 105, children: [] },
        ],
      },
    ],
  },

  // ==========================================
  // 2. CLOTHING & FASHION
  // ==========================================
  {
    id: 2,
    name: "Clothing & Fashion",
    slug: "clothing-fashion",
    parentId: null,
    children: [
      {
        id: 201,
        name: "Men's Clothing",
        slug: "mens-clothing",
        parentId: 2,
        children: [
          { id: 2011, name: "T-Shirts & Polos",   slug: "t-shirts-polos",      parentId: 201, children: [] },
          { id: 2012, name: "Jeans & Trousers",   slug: "mens-jeans-trousers", parentId: 201, children: [] },
          { id: 2013, name: "Formal Shirts",       slug: "formal-shirts",       parentId: 201, children: [] },
          { id: 2014, name: "Suits & Blazers",     slug: "suits-blazers",       parentId: 201, children: [] },
          { id: 2015, name: "Activewear",          slug: "mens-activewear",     parentId: 201, children: [] },
          { id: 2016, name: "Jackets & Coats",     slug: "mens-jackets-coats",  parentId: 201, children: [] },
          { id: 2017, name: "Shorts",              slug: "mens-shorts",         parentId: 201, children: [] },
          { id: 2018, name: "Ethnic Wear",         slug: "mens-ethnic-wear",    parentId: 201, children: [] },
          { id: 2019, name: "Innerwear",           slug: "mens-innerwear",      parentId: 201, children: [] },
          { id: 2020, name: "Sleepwear",           slug: "mens-sleepwear",      parentId: 201, children: [] },
        ],
      },
      {
        id: 202,
        name: "Women's Clothing",
        slug: "womens-clothing",
        parentId: 2,
        children: [
          { id: 2021, name: "Tops & Blouses",       slug: "tops-blouses",          parentId: 202, children: [] },
          { id: 2022, name: "Dresses & Jumpsuits",  slug: "dresses-jumpsuits",     parentId: 202, children: [] },
          { id: 2023, name: "Sarees & Kurtis",      slug: "sarees-kurtis",         parentId: 202, children: [] },
          { id: 2024, name: "Jeans & Trousers",     slug: "womens-jeans-trousers", parentId: 202, children: [] },
          { id: 2025, name: "Activewear",           slug: "womens-activewear",     parentId: 202, children: [] },
          { id: 2026, name: "Jackets & Coats",      slug: "womens-jackets-coats",  parentId: 202, children: [] },
          { id: 2027, name: "Skirts",               slug: "skirts",                parentId: 202, children: [] },
          { id: 2028, name: "Ethnic Wear",          slug: "womens-ethnic-wear",    parentId: 202, children: [] },
          { id: 2029, name: "Innerwear & Lingerie", slug: "innerwear-lingerie",    parentId: 202, children: [] },
          { id: 2030, name: "Sleepwear",            slug: "womens-sleepwear",      parentId: 202, children: [] },
        ],
      },
      {
        id: 203,
        name: "Kids' Clothing",
        slug: "kids-clothing",
        parentId: 2,
        children: [
          { id: 2031, name: "Boys' Tops",        slug: "boys-tops",        parentId: 203, children: [] },
          { id: 2032, name: "Girls' Tops",       slug: "girls-tops",       parentId: 203, children: [] },
          { id: 2033, name: "Boys' Bottoms",     slug: "boys-bottoms",     parentId: 203, children: [] },
          { id: 2034, name: "Girls' Dresses",    slug: "girls-dresses",    parentId: 203, children: [] },
          { id: 2035, name: "Baby Clothing",     slug: "baby-clothing",    parentId: 203, children: [] },
          { id: 2036, name: "School Uniforms",   slug: "school-uniforms",  parentId: 203, children: [] },
          { id: 2037, name: "Party Wear",        slug: "kids-party-wear",  parentId: 203, children: [] },
          { id: 2038, name: "Ethnic Kids Wear",  slug: "ethnic-kids-wear", parentId: 203, children: [] },
          { id: 2039, name: "Kids' Innerwear",   slug: "kids-innerwear",   parentId: 203, children: [] },
          { id: 2040, name: "Kids' Sleepwear",   slug: "kids-sleepwear",   parentId: 203, children: [] },
        ],
      },
      {
        id: 204,
        name: "Footwear",
        slug: "footwear",
        parentId: 2,
        children: [
          { id: 2041, name: "Men's Sneakers",      slug: "mens-sneakers",    parentId: 204, children: [] },
          { id: 2042, name: "Women's Heels",       slug: "womens-heels",     parentId: 204, children: [] },
          { id: 2043, name: "Sandals & Slippers",  slug: "sandals-slippers", parentId: 204, children: [] },
          { id: 2044, name: "Formal Shoes",        slug: "formal-shoes",     parentId: 204, children: [] },
          { id: 2045, name: "Sports Shoes",        slug: "sports-shoes",     parentId: 204, children: [] },
          { id: 2046, name: "Boots",               slug: "boots",            parentId: 204, children: [] },
          { id: 2047, name: "Kids' Shoes",         slug: "kids-shoes",       parentId: 204, children: [] },
          { id: 2048, name: "Loafers & Moccasins", slug: "loafers-moccasins",parentId: 204, children: [] },
          { id: 2049, name: "Flip Flops",          slug: "flip-flops",       parentId: 204, children: [] },
          { id: 2050, name: "Ethnic Footwear",     slug: "ethnic-footwear",  parentId: 204, children: [] },
        ],
      },
      {
        id: 205,
        name: "Accessories & Bags",
        slug: "accessories-bags",
        parentId: 2,
        children: [
          { id: 2051, name: "Handbags",              slug: "handbags",             parentId: 205, children: [] },
          { id: 2052, name: "Backpacks",             slug: "backpacks",            parentId: 205, children: [] },
          { id: 2053, name: "Wallets",               slug: "wallets",              parentId: 205, children: [] },
          { id: 2054, name: "Belts",                 slug: "belts",                parentId: 205, children: [] },
          { id: 2055, name: "Sunglasses",            slug: "sunglasses",           parentId: 205, children: [] },
          { id: 2056, name: "Watches",               slug: "watches",              parentId: 205, children: [] },
          { id: 2057, name: "Scarves & Stoles",      slug: "scarves-stoles",       parentId: 205, children: [] },
          { id: 2058, name: "Hats & Caps",           slug: "hats-caps",            parentId: 205, children: [] },
          { id: 2059, name: "Jewellery",             slug: "jewellery",            parentId: 205, children: [] },
          { id: 2060, name: "Luggage & Travel Bags", slug: "luggage-travel-bags",  parentId: 205, children: [] },
        ],
      },
    ],
  },

  // ==========================================
  // 3. HOME & KITCHEN
  // ==========================================
  {
    id: 3,
    name: "Home & Kitchen",
    slug: "home-kitchen",
    parentId: null,
    children: [
      {
        id: 301,
        name: "Cookware & Bakeware",
        slug: "cookware-bakeware",
        parentId: 3,
        children: [
          { id: 3011, name: "Frying Pans",       slug: "frying-pans",       parentId: 301, children: [] },
          { id: 3012, name: "Pressure Cookers",  slug: "pressure-cookers",  parentId: 301, children: [] },
          { id: 3013, name: "Cooking Pots",      slug: "cooking-pots",      parentId: 301, children: [] },
          { id: 3014, name: "Baking Trays",      slug: "baking-trays",      parentId: 301, children: [] },
          { id: 3015, name: "Non-Stick Cookware",slug: "non-stick-cookware",parentId: 301, children: [] },
          { id: 3016, name: "Cast Iron Cookware",slug: "cast-iron-cookware",parentId: 301, children: [] },
          { id: 3017, name: "Woks & Kadais",     slug: "woks-kadais",       parentId: 301, children: [] },
          { id: 3018, name: "Baking Moulds",     slug: "baking-moulds",     parentId: 301, children: [] },
          { id: 3019, name: "Cooking Utensils",  slug: "cooking-utensils",  parentId: 301, children: [] },
          { id: 3020, name: "Kitchen Knives",    slug: "kitchen-knives",    parentId: 301, children: [] },
        ],
      },
      {
        id: 302,
        name: "Kitchen Appliances",
        slug: "kitchen-appliances",
        parentId: 3,
        children: [
          { id: 3021, name: "Refrigerators",       slug: "refrigerators",       parentId: 302, children: [] },
          { id: 3022, name: "Microwave Ovens",     slug: "microwave-ovens",     parentId: 302, children: [] },
          { id: 3023, name: "Blenders & Mixers",   slug: "blenders-mixers",     parentId: 302, children: [] },
          { id: 3024, name: "Air Fryers",          slug: "air-fryers",          parentId: 302, children: [] },
          { id: 3025, name: "Toasters",            slug: "toasters",            parentId: 302, children: [] },
          { id: 3026, name: "Coffee Makers",       slug: "coffee-makers",       parentId: 302, children: [] },
          { id: 3027, name: "Rice Cookers",        slug: "rice-cookers",        parentId: 302, children: [] },
          { id: 3028, name: "Dishwashers",         slug: "dishwashers",         parentId: 302, children: [] },
          { id: 3029, name: "Induction Cooktops",  slug: "induction-cooktops",  parentId: 302, children: [] },
          { id: 3030, name: "Food Processors",     slug: "food-processors",     parentId: 302, children: [] },
        ],
      },
      {
        id: 303,
        name: "Furniture",
        slug: "furniture",
        parentId: 3,
        children: [
          { id: 3031, name: "Sofas & Couches",    slug: "sofas-couches",    parentId: 303, children: [] },
          { id: 3032, name: "Dining Tables",      slug: "dining-tables",    parentId: 303, children: [] },
          { id: 3033, name: "Beds & Bed Frames",  slug: "beds-bed-frames",  parentId: 303, children: [] },
          { id: 3034, name: "Wardrobes",          slug: "wardrobes",        parentId: 303, children: [] },
          { id: 3035, name: "Study Desks",        slug: "study-desks",      parentId: 303, children: [] },
          { id: 3036, name: "Bookshelves",        slug: "bookshelves",      parentId: 303, children: [] },
          { id: 3037, name: "Coffee Tables",      slug: "coffee-tables",    parentId: 303, children: [] },
          { id: 3038, name: "TV Units",           slug: "tv-units",         parentId: 303, children: [] },
          { id: 3039, name: "Chairs",             slug: "chairs",           parentId: 303, children: [] },
          { id: 3040, name: "Storage Cabinets",   slug: "storage-cabinets", parentId: 303, children: [] },
        ],
      },
      {
        id: 304,
        name: "Bedding & Bath",
        slug: "bedding-bath",
        parentId: 3,
        children: [
          { id: 3041, name: "Bed Sheets",        slug: "bed-sheets",       parentId: 304, children: [] },
          { id: 3042, name: "Pillows",           slug: "pillows",          parentId: 304, children: [] },
          { id: 3043, name: "Blankets & Quilts", slug: "blankets-quilts",  parentId: 304, children: [] },
          { id: 3044, name: "Mattresses",        slug: "mattresses",       parentId: 304, children: [] },
          { id: 3045, name: "Bath Towels",       slug: "bath-towels",      parentId: 304, children: [] },
          { id: 3046, name: "Curtains",          slug: "curtains",         parentId: 304, children: [] },
          { id: 3047, name: "Cushion Covers",    slug: "cushion-covers",   parentId: 304, children: [] },
          { id: 3048, name: "Shower Curtains",   slug: "shower-curtains",  parentId: 304, children: [] },
          { id: 3049, name: "Bath Mats",         slug: "bath-mats",        parentId: 304, children: [] },
          { id: 3050, name: "Mosquito Nets",     slug: "mosquito-nets",    parentId: 304, children: [] },
        ],
      },
      {
        id: 305,
        name: "Home Décor",
        slug: "home-decor",
        parentId: 3,
        children: [
          { id: 3051, name: "Wall Art & Paintings",    slug: "wall-art-paintings",   parentId: 305, children: [] },
          { id: 3052, name: "Photo Frames",            slug: "photo-frames",         parentId: 305, children: [] },
          { id: 3053, name: "Candles & Holders",       slug: "candles-holders",      parentId: 305, children: [] },
          { id: 3054, name: "Vases & Planters",        slug: "vases-planters",       parentId: 305, children: [] },
          { id: 3055, name: "Clocks",                  slug: "clocks",               parentId: 305, children: [] },
          { id: 3056, name: "Mirrors",                 slug: "mirrors",              parentId: 305, children: [] },
          { id: 3057, name: "Artificial Plants",       slug: "artificial-plants",    parentId: 305, children: [] },
          { id: 3058, name: "Rugs & Carpets",          slug: "rugs-carpets",         parentId: 305, children: [] },
          { id: 3059, name: "Table Lamps",             slug: "table-lamps",          parentId: 305, children: [] },
          { id: 3060, name: "Figurines & Showpieces",  slug: "figurines-showpieces", parentId: 305, children: [] },
        ],
      },
    ],
  },

  // ==========================================
  // 4. BEAUTY & PERSONAL CARE
  // ==========================================
  {
    id: 4,
    name: "Beauty & Personal Care",
    slug: "beauty-personal-care",
    parentId: null,
    children: [
      {
        id: 401,
        name: "Skincare",
        slug: "skincare",
        parentId: 4,
        children: [
          { id: 4011, name: "Face Wash & Cleansers", slug: "face-wash-cleansers", parentId: 401, children: [] },
          { id: 4012, name: "Moisturisers",          slug: "moisturisers",        parentId: 401, children: [] },
          { id: 4013, name: "Sunscreens",            slug: "sunscreens",          parentId: 401, children: [] },
          { id: 4014, name: "Face Serums",           slug: "face-serums",         parentId: 401, children: [] },
          { id: 4015, name: "Toners",                slug: "toners",              parentId: 401, children: [] },
          { id: 4016, name: "Eye Creams",            slug: "eye-creams",          parentId: 401, children: [] },
          { id: 4017, name: "Face Masks",            slug: "face-masks",          parentId: 401, children: [] },
          { id: 4018, name: "Lip Balms",             slug: "lip-balms",           parentId: 401, children: [] },
          { id: 4019, name: "Night Creams",          slug: "night-creams",        parentId: 401, children: [] },
          { id: 4020, name: "Exfoliators",           slug: "exfoliators",         parentId: 401, children: [] },
        ],
      },
      {
        id: 402,
        name: "Hair Care",
        slug: "hair-care",
        parentId: 4,
        children: [
          { id: 4021, name: "Shampoos",                slug: "shampoos",                parentId: 402, children: [] },
          { id: 4022, name: "Conditioners",            slug: "conditioners",            parentId: 402, children: [] },
          { id: 4023, name: "Hair Oils",               slug: "hair-oils",               parentId: 402, children: [] },
          { id: 4024, name: "Hair Masks",              slug: "hair-masks",              parentId: 402, children: [] },
          { id: 4025, name: "Hair Serums",             slug: "hair-serums",             parentId: 402, children: [] },
          { id: 4026, name: "Hair Colour",             slug: "hair-colour",             parentId: 402, children: [] },
          { id: 4027, name: "Hair Dryers",             slug: "hair-dryers",             parentId: 402, children: [] },
          { id: 4028, name: "Straighteners & Curlers", slug: "straighteners-curlers",   parentId: 402, children: [] },
          { id: 4029, name: "Hair Growth Products",    slug: "hair-growth-products",    parentId: 402, children: [] },
          { id: 4030, name: "Dry Shampoos",            slug: "dry-shampoos",            parentId: 402, children: [] },
        ],
      },
      {
        id: 403,
        name: "Makeup & Cosmetics",
        slug: "makeup-cosmetics",
        parentId: 4,
        children: [
          { id: 4031, name: "Foundations",         slug: "foundations",         parentId: 403, children: [] },
          { id: 4032, name: "Lipsticks & Lip Gloss",slug: "lipsticks-lip-gloss",parentId: 403, children: [] },
          { id: 4033, name: "Mascaras",            slug: "mascaras",            parentId: 403, children: [] },
          { id: 4034, name: "Eyeshadow Palettes",  slug: "eyeshadow-palettes",  parentId: 403, children: [] },
          { id: 4035, name: "Blush & Bronzers",    slug: "blush-bronzers",      parentId: 403, children: [] },
          { id: 4036, name: "Eyeliners",           slug: "eyeliners",           parentId: 403, children: [] },
          { id: 4037, name: "Nail Polish",         slug: "nail-polish",         parentId: 403, children: [] },
          { id: 4038, name: "Concealers",          slug: "concealers",          parentId: 403, children: [] },
          { id: 4039, name: "Setting Sprays",      slug: "setting-sprays",      parentId: 403, children: [] },
          { id: 4040, name: "Makeup Brushes",      slug: "makeup-brushes",      parentId: 403, children: [] },
        ],
      },
      {
        id: 404,
        name: "Fragrances",
        slug: "fragrances",
        parentId: 4,
        children: [
          { id: 4041, name: "Men's Perfumes",     slug: "mens-perfumes",     parentId: 404, children: [] },
          { id: 4042, name: "Women's Perfumes",   slug: "womens-perfumes",   parentId: 404, children: [] },
          { id: 4043, name: "Unisex Fragrances",  slug: "unisex-fragrances", parentId: 404, children: [] },
          { id: 4044, name: "Body Mists",         slug: "body-mists",        parentId: 404, children: [] },
          { id: 4045, name: "Deodorants",         slug: "deodorants",        parentId: 404, children: [] },
          { id: 4046, name: "Attar & Oud",        slug: "attar-oud",         parentId: 404, children: [] },
          { id: 4047, name: "Room Fresheners",    slug: "room-fresheners",   parentId: 404, children: [] },
          { id: 4048, name: "Car Fresheners",     slug: "car-fresheners",    parentId: 404, children: [] },
          { id: 4049, name: "Gift Sets",          slug: "fragrance-gift-sets",parentId: 404, children: [] },
          { id: 4050, name: "Essential Oils",     slug: "essential-oils",    parentId: 404, children: [] },
        ],
      },
      {
        id: 405,
        name: "Personal Hygiene",
        slug: "personal-hygiene",
        parentId: 4,
        children: [
          { id: 4051, name: "Soaps & Body Wash",       slug: "soaps-body-wash",      parentId: 405, children: [] },
          { id: 4052, name: "Toothbrushes & Toothpaste",slug: "toothbrushes-toothpaste",parentId: 405, children: [] },
          { id: 4053, name: "Razors & Shavers",        slug: "razors-shavers",       parentId: 405, children: [] },
          { id: 4054, name: "Feminine Care",           slug: "feminine-care",        parentId: 405, children: [] },
          { id: 4055, name: "Oral Care",               slug: "oral-care",            parentId: 405, children: [] },
          { id: 4056, name: "Cotton & Swabs",          slug: "cotton-swabs",         parentId: 405, children: [] },
          { id: 4057, name: "Hand Sanitisers",         slug: "hand-sanitisers",      parentId: 405, children: [] },
          { id: 4058, name: "Intimate Wash",           slug: "intimate-wash",        parentId: 405, children: [] },
          { id: 4059, name: "Hair Removal",            slug: "hair-removal",         parentId: 405, children: [] },
          { id: 4060, name: "Wet Wipes",               slug: "wet-wipes",            parentId: 405, children: [] },
        ],
      },
    ],
  },

  // ==========================================
  // 5. SPORTS & OUTDOORS
  // ==========================================
  {
    id: 5,
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    parentId: null,
    children: [
      {
        id: 501,
        name: "Exercise & Fitness",
        slug: "exercise-fitness",
        parentId: 5,
        children: [
          { id: 5011, name: "Dumbbells & Weights",  slug: "dumbbells-weights",  parentId: 501, children: [] },
          { id: 5012, name: "Resistance Bands",     slug: "resistance-bands",   parentId: 501, children: [] },
          { id: 5013, name: "Yoga Mats & Blocks",   slug: "yoga-mats-blocks",   parentId: 501, children: [] },
          { id: 5014, name: "Treadmills",           slug: "treadmills",         parentId: 501, children: [] },
          { id: 5015, name: "Exercise Bikes",       slug: "exercise-bikes",     parentId: 501, children: [] },
          { id: 5016, name: "Gym Gloves & Belts",   slug: "gym-gloves-belts",   parentId: 501, children: [] },
          { id: 5017, name: "Protein Supplements",  slug: "protein-supplements",parentId: 501, children: [] },
          { id: 5018, name: "Pull-Up Bars",         slug: "pull-up-bars",       parentId: 501, children: [] },
          { id: 5019, name: "Kettlebells",          slug: "kettlebells",        parentId: 501, children: [] },
          { id: 5020, name: "Jump Ropes",           slug: "jump-ropes",         parentId: 501, children: [] },
        ],
      },
      {
        id: 502,
        name: "Outdoor Recreation",
        slug: "outdoor-recreation",
        parentId: 5,
        children: [
          { id: 5021, name: "Camping Tents",          slug: "camping-tents",         parentId: 502, children: [] },
          { id: 5022, name: "Sleeping Bags",          slug: "sleeping-bags",         parentId: 502, children: [] },
          { id: 5023, name: "Hiking Boots",           slug: "hiking-boots",          parentId: 502, children: [] },
          { id: 5024, name: "Trekking Poles",         slug: "trekking-poles",        parentId: 502, children: [] },
          { id: 5025, name: "Backpacks & Rucksacks",  slug: "backpacks-rucksacks",   parentId: 502, children: [] },
          { id: 5026, name: "Hammocks",               slug: "hammocks",              parentId: 502, children: [] },
          { id: 5027, name: "Headlamps",              slug: "headlamps",             parentId: 502, children: [] },
          { id: 5028, name: "Portable Stoves",        slug: "portable-stoves",       parentId: 502, children: [] },
          { id: 5029, name: "Compasses & GPS",        slug: "compasses-gps",         parentId: 502, children: [] },
          { id: 5030, name: "Survival Kits",          slug: "survival-kits",         parentId: 502, children: [] },
        ],
      },
      {
        id: 503,
        name: "Team Sports",
        slug: "team-sports",
        parentId: 5,
        children: [
          { id: 5031, name: "Football & Soccer",    slug: "football-soccer",   parentId: 503, children: [] },
          { id: 5032, name: "Cricket Equipment",    slug: "cricket-equipment", parentId: 503, children: [] },
          { id: 5033, name: "Basketball & Hoops",   slug: "basketball-hoops",  parentId: 503, children: [] },
          { id: 5034, name: "Badminton Rackets",    slug: "badminton-rackets", parentId: 503, children: [] },
          { id: 5035, name: "Table Tennis",         slug: "table-tennis",      parentId: 503, children: [] },
          { id: 5036, name: "Volleyball",           slug: "volleyball",        parentId: 503, children: [] },
          { id: 5037, name: "Hockey Sticks",        slug: "hockey-sticks",     parentId: 503, children: [] },
          { id: 5038, name: "Rugby Balls",          slug: "rugby-balls",       parentId: 503, children: [] },
          { id: 5039, name: "Baseball Equipment",   slug: "baseball-equipment",parentId: 503, children: [] },
          { id: 5040, name: "Kabaddi & Wrestling",  slug: "kabaddi-wrestling", parentId: 503, children: [] },
        ],
      },
      {
        id: 504,
        name: "Water Sports",
        slug: "water-sports",
        parentId: 5,
        children: [
          { id: 5041, name: "Swimming Goggles",  slug: "swimming-goggles",  parentId: 504, children: [] },
          { id: 5042, name: "Swimwear",          slug: "swimwear",          parentId: 504, children: [] },
          { id: 5043, name: "Swim Caps",         slug: "swim-caps",         parentId: 504, children: [] },
          { id: 5044, name: "Surfboards",        slug: "surfboards",        parentId: 504, children: [] },
          { id: 5045, name: "Kayaks & Paddles",  slug: "kayaks-paddles",    parentId: 504, children: [] },
          { id: 5046, name: "Life Jackets",      slug: "life-jackets",      parentId: 504, children: [] },
          { id: 5047, name: "Snorkelling Gear",  slug: "snorkelling-gear",  parentId: 504, children: [] },
          { id: 5048, name: "Water Polo",        slug: "water-polo",        parentId: 504, children: [] },
          { id: 5049, name: "Diving Equipment",  slug: "diving-equipment",  parentId: 504, children: [] },
          { id: 5050, name: "Inflatable Boats",  slug: "inflatable-boats",  parentId: 504, children: [] },
        ],
      },
      {
        id: 505,
        name: "Cycling",
        slug: "cycling",
        parentId: 5,
        children: [
          { id: 5051, name: "Road Bikes",          slug: "road-bikes",         parentId: 505, children: [] },
          { id: 5052, name: "Mountain Bikes",      slug: "mountain-bikes",     parentId: 505, children: [] },
          { id: 5053, name: "Kids' Bicycles",      slug: "kids-bicycles",      parentId: 505, children: [] },
          { id: 5054, name: "E-Bikes",             slug: "e-bikes",            parentId: 505, children: [] },
          { id: 5055, name: "Cycling Helmets",     slug: "cycling-helmets",    parentId: 505, children: [] },
          { id: 5056, name: "Cycling Gloves",      slug: "cycling-gloves",     parentId: 505, children: [] },
          { id: 5057, name: "Bike Locks",          slug: "bike-locks",         parentId: 505, children: [] },
          { id: 5058, name: "Bike Lights",         slug: "bike-lights",        parentId: 505, children: [] },
          { id: 5059, name: "Saddles & Seats",     slug: "saddles-seats",      parentId: 505, children: [] },
          { id: 5060, name: "Bike Repair Tools",   slug: "bike-repair-tools",  parentId: 505, children: [] },
        ],
      },
    ],
  },

  // ==========================================
  // 6. TOYS & GAMES
  // ==========================================
  {
    id: 6,
    name: "Toys & Games",
    slug: "toys-games",
    parentId: null,
    children: [
      {
        id: 601,
        name: "Action Figures & Dolls",
        slug: "action-figures-dolls",
        parentId: 6,
        children: [
          { id: 6011, name: "Superhero Figures",   slug: "superhero-figures",  parentId: 601, children: [] },
          { id: 6012, name: "Barbie Dolls",        slug: "barbie-dolls",       parentId: 601, children: [] },
          { id: 6013, name: "Anime Figures",       slug: "anime-figures",      parentId: 601, children: [] },
          { id: 6014, name: "Baby Dolls",          slug: "baby-dolls",         parentId: 601, children: [] },
          { id: 6015, name: "Military Figures",    slug: "military-figures",   parentId: 601, children: [] },
          { id: 6016, name: "Dinosaur Figures",    slug: "dinosaur-figures",   parentId: 601, children: [] },
          { id: 6017, name: "Disney Characters",   slug: "disney-characters",  parentId: 601, children: [] },
          { id: 6018, name: "Doll Accessories",    slug: "doll-accessories",   parentId: 601, children: [] },
          { id: 6019, name: "Puppet Toys",         slug: "puppet-toys",        parentId: 601, children: [] },
          { id: 6020, name: "Collectible Figures", slug: "collectible-figures",parentId: 601, children: [] },
        ],
      },
      {
        id: 602,
        name: "Board Games",
        slug: "board-games",
        parentId: 6,
        children: [
          { id: 6021, name: "Chess & Checkers",         slug: "chess-checkers",        parentId: 602, children: [] },
          { id: 6022, name: "Scrabble",                 slug: "scrabble",              parentId: 602, children: [] },
          { id: 6023, name: "Monopoly",                 slug: "monopoly",              parentId: 602, children: [] },
          { id: 6024, name: "Ludo & Snakes & Ladders",  slug: "ludo-snakes-ladders",   parentId: 602, children: [] },
          { id: 6025, name: "Card Games",               slug: "card-games",            parentId: 602, children: [] },
          { id: 6026, name: "Puzzles",                  slug: "puzzles",               parentId: 602, children: [] },
          { id: 6027, name: "Trivia Games",             slug: "trivia-games",          parentId: 602, children: [] },
          { id: 6028, name: "Strategy Games",           slug: "strategy-games",        parentId: 602, children: [] },
          { id: 6029, name: "Party Games",              slug: "party-games",           parentId: 602, children: [] },
          { id: 6030, name: "Dominos & Dice",           slug: "dominos-dice",          parentId: 602, children: [] },
        ],
      },
      {
        id: 603,
        name: "Building & Construction",
        slug: "building-construction",
        parentId: 6,
        children: [
          { id: 6031, name: "LEGO Sets",           slug: "lego-sets",          parentId: 603, children: [] },
          { id: 6032, name: "Magnetic Tiles",      slug: "magnetic-tiles",     parentId: 603, children: [] },
          { id: 6033, name: "Wooden Blocks",       slug: "wooden-blocks",      parentId: 603, children: [] },
          { id: 6034, name: "Marble Runs",         slug: "marble-runs",        parentId: 603, children: [] },
          { id: 6035, name: "Erector Sets",        slug: "erector-sets",       parentId: 603, children: [] },
          { id: 6036, name: "Foam Blocks",         slug: "foam-blocks",        parentId: 603, children: [] },
          { id: 6037, name: "Castle & City Sets",  slug: "castle-city-sets",   parentId: 603, children: [] },
          { id: 6038, name: "Train Sets",          slug: "train-sets",         parentId: 603, children: [] },
          { id: 6039, name: "Architecture Kits",   slug: "architecture-kits",  parentId: 603, children: [] },
          { id: 6040, name: "STEM Building Kits",  slug: "stem-building-kits", parentId: 603, children: [] },
        ],
      },
      {
        id: 604,
        name: "Electronic Toys",
        slug: "electronic-toys",
        parentId: 6,
        children: [
          { id: 6041, name: "Remote Control Cars",     slug: "remote-control-cars",  parentId: 604, children: [] },
          { id: 6042, name: "Drones for Kids",         slug: "drones-for-kids",      parentId: 604, children: [] },
          { id: 6043, name: "Educational Tablets",     slug: "educational-tablets",  parentId: 604, children: [] },
          { id: 6044, name: "Robot Toys",              slug: "robot-toys",           parentId: 604, children: [] },
          { id: 6045, name: "Electronic Learning",     slug: "electronic-learning",  parentId: 604, children: [] },
          { id: 6046, name: "Video Game Toys",         slug: "video-game-toys",      parentId: 604, children: [] },
          { id: 6047, name: "Walkie Talkies",          slug: "walkie-talkies",       parentId: 604, children: [] },
          { id: 6048, name: "Musical Toys",            slug: "musical-toys",         parentId: 604, children: [] },
          { id: 6049, name: "Interactive Pets",        slug: "interactive-pets",     parentId: 604, children: [] },
          { id: 6050, name: "Coding Toys",             slug: "coding-toys",          parentId: 604, children: [] },
        ],
      },
      {
        id: 605,
        name: "Outdoor Play",
        slug: "outdoor-play",
        parentId: 6,
        children: [
          { id: 6051, name: "Swings & Slides",    slug: "swings-slides",    parentId: 605, children: [] },
          { id: 6052, name: "Trampolines",        slug: "trampolines",      parentId: 605, children: [] },
          { id: 6053, name: "Water Guns & Toys",  slug: "water-guns-toys",  parentId: 605, children: [] },
          { id: 6054, name: "Sandpit Toys",       slug: "sandpit-toys",     parentId: 605, children: [] },
          { id: 6055, name: "Kites",              slug: "kites",            parentId: 605, children: [] },
          { id: 6056, name: "Scooters",           slug: "scooters",         parentId: 605, children: [] },
          { id: 6057, name: "Balance Bikes",      slug: "balance-bikes",    parentId: 605, children: [] },
          { id: 6058, name: "Bubbles & Blowers",  slug: "bubbles-blowers",  parentId: 605, children: [] },
          { id: 6059, name: "Sports Toys",        slug: "sports-toys",      parentId: 605, children: [] },
          { id: 6060, name: "Play Tents & Tunnels",slug: "play-tents-tunnels",parentId: 605, children: [] },
        ],
      },
    ],
  },

  // ==========================================
  // 7. AUTOMOTIVE
  // ==========================================
  {
    id: 7,
    name: "Automotive",
    slug: "automotive",
    parentId: null,
    children: [
      {
        id: 701,
        name: "Car Electronics",
        slug: "car-electronics",
        parentId: 7,
        children: [
          { id: 7011, name: "Car Stereos",         slug: "car-stereos",        parentId: 701, children: [] },
          { id: 7012, name: "GPS & Navigation",    slug: "gps-navigation",     parentId: 701, children: [] },
          { id: 7013, name: "Dash Cameras",        slug: "dash-cameras",       parentId: 701, children: [] },
          { id: 7014, name: "Car Chargers",        slug: "car-chargers",       parentId: 701, children: [] },
          { 
            id: 7015, 
            name: "Parking Sensors",     
            slug: "parking-sensors",    
            parentId: 701, children: [
              {
                id: 100000,
                name: "Fiction Books",
                slug: "fiction-books",
                parentId: 7015,
                children: [
                  { id: 8011, name: "Literary Fiction",    slug: "literary-fiction",   parentId: 801, children: [] },
                  { id: 8012, name: "Mystery & Thrillers", slug: "mystery-thrillers",  parentId: 801, children: [] },
                  { id: 8013, name: "Science Fiction",     slug: "science-fiction",    parentId: 801, children: [] },
                  { id: 8014, name: "Fantasy",             slug: "fantasy",            parentId: 801, children: [] },
                  { id: 8015, name: "Romance Novels",      slug: "romance-novels",     parentId: 801, children: [] },
                  { id: 8016, name: "Horror & Supernatural",slug: "horror-supernatural",parentId: 801, children: [] },
                  { id: 8017, name: "Historical Fiction",  slug: "historical-fiction", parentId: 801, children: [] },
                  { id: 8018, name: "Adventure",           slug: "adventure",          parentId: 801, children: [] },
                  { id: 8019, name: "Graphic Novels",      slug: "graphic-novels",     parentId: 801, children: [] },
                  { id: 8020, name: "Bengali Fiction",     slug: "bengali-fiction",    parentId: 801, children: [] },
                ],
              },
            ]
          },
          { id: 7016, name: "Bluetooth Car Kits",  slug: "bluetooth-car-kits", parentId: 701, children: [] },
          { id: 7017, name: "Car Amplifiers",      slug: "car-amplifiers",     parentId: 701, children: [] },
          { id: 7018, name: "Reversing Cameras",   slug: "reversing-cameras",  parentId: 701, children: [] },
          { id: 7019, name: "Head-Up Displays",    slug: "head-up-displays",   parentId: 701, children: [] },
          { id: 7020, name: "Car TV Screens",      slug: "car-tv-screens",     parentId: 701, children: [] },
        ],
      },
      {
        id: 702,
        name: "Car Care & Cleaning",
        slug: "car-care-cleaning",
        parentId: 7,
        children: [
          { id: 7021, name: "Car Shampoos",        slug: "car-shampoos",       parentId: 702, children: [] },
          { id: 7022, name: "Car Wax & Polish",    slug: "car-wax-polish",     parentId: 702, children: [] },
          { id: 7023, name: "Tyre Cleaners",       slug: "tyre-cleaners",      parentId: 702, children: [] },
          { id: 7024, name: "Interior Cleaners",   slug: "interior-cleaners",  parentId: 702, children: [] },
          { id: 7025, name: "Microfibre Cloths",   slug: "microfibre-cloths",  parentId: 702, children: [] },
          { id: 7026, name: "Car Vacuum Cleaners", slug: "car-vacuum-cleaners",parentId: 702, children: [] },
          { id: 7027, name: "Windscreen Cleaners", slug: "windscreen-cleaners",parentId: 702, children: [] },
          { id: 7028, name: "Engine Cleaners",     slug: "engine-cleaners",    parentId: 702, children: [] },
          { id: 7029, name: "Air Fresheners",      slug: "air-fresheners",     parentId: 702, children: [] },
          { id: 7030, name: "Scratch Removers",    slug: "scratch-removers",   parentId: 702, children: [] },
        ],
      },
      {
        id: 703,
        name: "Interior Accessories",
        slug: "interior-accessories",
        parentId: 7,
        children: [
          { id: 7031, name: "Seat Covers",           slug: "seat-covers",          parentId: 703, children: [] },
          { id: 7032, name: "Car Mats & Carpets",    slug: "car-mats-carpets",     parentId: 703, children: [] },
          { id: 7033, name: "Steering Wheel Covers", slug: "steering-wheel-covers",parentId: 703, children: [] },
          { id: 7034, name: "Sunshades",             slug: "sunshades",            parentId: 703, children: [] },
          { id: 7035, name: "Car Organisers",        slug: "car-organisers",       parentId: 703, children: [] },
          { id: 7036, name: "Phone Holders",         slug: "phone-holders",        parentId: 703, children: [] },
          { id: 7037, name: "Neck & Seat Pillows",   slug: "neck-seat-pillows",    parentId: 703, children: [] },
          { id: 7038, name: "Gear Shift Covers",     slug: "gear-shift-covers",    parentId: 703, children: [] },
          { id: 7039, name: "Child Car Seats",       slug: "child-car-seats",      parentId: 703, children: [] },
          { id: 7040, name: "Car Curtains",          slug: "car-curtains",         parentId: 703, children: [] },
        ],
      },
      {
        id: 704,
        name: "Exterior Accessories",
        slug: "exterior-accessories",
        parentId: 7,
        children: [
          { id: 7041, name: "Car Body Covers",       slug: "car-body-covers",      parentId: 704, children: [] },
          { id: 7042, name: "Roof Racks",            slug: "roof-racks",           parentId: 704, children: [] },
          { id: 7043, name: "Tow Bars",              slug: "tow-bars",             parentId: 704, children: [] },
          { id: 7044, name: "Mud Guards",            slug: "mud-guards",           parentId: 704, children: [] },
          { id: 7045, name: "Spoilers",              slug: "spoilers",             parentId: 704, children: [] },
          { id: 7046, name: "Antenna",               slug: "antenna",              parentId: 704, children: [] },
          { id: 7047, name: "Side Mirrors",          slug: "side-mirrors",         parentId: 704, children: [] },
          { id: 7048, name: "Number Plate Frames",   slug: "number-plate-frames",  parentId: 704, children: [] },
          { id: 7049, name: "Car Stickers & Decals", slug: "car-stickers-decals",  parentId: 704, children: [] },
          { id: 7050, name: "Alloy Wheel Covers",    slug: "alloy-wheel-covers",   parentId: 704, children: [] },
        ],
      },
      {
        id: 705,
        name: "Tools & Equipment",
        slug: "tools-equipment",
        parentId: 7,
        children: [
          { id: 7051, name: "Car Jacks",             slug: "car-jacks",            parentId: 705, children: [] },
          { id: 7052, name: "Tyre Inflators",        slug: "tyre-inflators",       parentId: 705, children: [] },
          { id: 7053, name: "Jumper Cables",         slug: "jumper-cables",        parentId: 705, children: [] },
          { id: 7054, name: "Torque Wrenches",       slug: "torque-wrenches",      parentId: 705, children: [] },
          { id: 7055, name: "OBD Scanners",          slug: "obd-scanners",         parentId: 705, children: [] },
          { id: 7056, name: "Tyre Pressure Gauges",  slug: "tyre-pressure-gauges", parentId: 705, children: [] },
          { id: 7057, name: "Jump Starters",         slug: "jump-starters",        parentId: 705, children: [] },
          { id: 7058, name: "Car Tool Kits",         slug: "car-tool-kits",        parentId: 705, children: [] },
          { id: 7059, name: "Battery Chargers",      slug: "battery-chargers",     parentId: 705, children: [] },
          { id: 7060, name: "Snow Chains",           slug: "snow-chains",          parentId: 705, children: [] },
        ],
      },
    ],
  },

  // ==========================================
  // 8. BOOKS & STATIONERY
  // ==========================================
  {
    id: 8,
    name: "Books & Stationery",
    slug: "books-stationery",
    parentId: null,
    children: [
      {
        id: 801,
        name: "Fiction Books",
        slug: "fiction-books",
        parentId: 8,
        children: [
          { id: 8011, name: "Literary Fiction",    slug: "literary-fiction",   parentId: 801, children: [] },
          { id: 8012, name: "Mystery & Thrillers", slug: "mystery-thrillers",  parentId: 801, children: [] },
          { id: 8013, name: "Science Fiction",     slug: "science-fiction",    parentId: 801, children: [] },
          { id: 8014, name: "Fantasy",             slug: "fantasy",            parentId: 801, children: [] },
          { id: 8015, name: "Romance Novels",      slug: "romance-novels",     parentId: 801, children: [] },
          { id: 8016, name: "Horror & Supernatural",slug: "horror-supernatural",parentId: 801, children: [] },
          { id: 8017, name: "Historical Fiction",  slug: "historical-fiction", parentId: 801, children: [] },
          { id: 8018, name: "Adventure",           slug: "adventure",          parentId: 801, children: [] },
          { id: 8019, name: "Graphic Novels",      slug: "graphic-novels",     parentId: 801, children: [] },
          { id: 8020, name: "Bengali Fiction",     slug: "bengali-fiction",    parentId: 801, children: [] },
        ],
      },
      {
        id: 802,
        name: "Non-Fiction Books",
        slug: "non-fiction-books",
        parentId: 8,
        children: [
          { id: 8021, name: "Biographies & Memoirs",  slug: "biographies-memoirs",  parentId: 802, children: [] },
          { id: 8022, name: "Self-Help & Motivation",  slug: "self-help-motivation", parentId: 802, children: [] },
          { id: 8023, name: "Business & Finance",      slug: "business-finance",     parentId: 802, children: [] },
          { id: 8024, name: "History & Politics",      slug: "history-politics",     parentId: 802, children: [] },
          { id: 8025, name: "Science & Nature",        slug: "science-nature",       parentId: 802, children: [] },
          { id: 8026, name: "Travel & Geography",      slug: "travel-geography",     parentId: 802, children: [] },
          { id: 8027, name: "Philosophy",              slug: "philosophy",           parentId: 802, children: [] },
          { id: 8028, name: "Religion & Spirituality", slug: "religion-spirituality",parentId: 802, children: [] },
          { id: 8029, name: "True Crime",              slug: "true-crime",           parentId: 802, children: [] },
          { id: 8030, name: "Psychology",              slug: "psychology",           parentId: 802, children: [] },
        ],
      },
      {
        id: 803,
        name: "Educational Books",
        slug: "educational-books",
        parentId: 8,
        children: [
          { id: 8031, name: "School Textbooks",        slug: "school-textbooks",        parentId: 803, children: [] },
          { id: 8032, name: "University Textbooks",    slug: "university-textbooks",    parentId: 803, children: [] },
          { id: 8033, name: "Competitive Exam Books",  slug: "competitive-exam-books",  parentId: 803, children: [] },
          { id: 8034, name: "Language Learning",       slug: "language-learning",       parentId: 803, children: [] },
          { id: 8035, name: "Children's Educational",  slug: "childrens-educational",   parentId: 803, children: [] },
          { id: 8036, name: "Science & Maths",         slug: "science-maths",           parentId: 803, children: [] },
          { id: 8037, name: "Engineering Books",       slug: "engineering-books",       parentId: 803, children: [] },
          { id: 8038, name: "Medical Books",           slug: "medical-books",           parentId: 803, children: [] },
          { id: 8039, name: "Law Books",               slug: "law-books",               parentId: 803, children: [] },
          { id: 8040, name: "Computer Science Books",  slug: "computer-science-books",  parentId: 803, children: [] },
        ],
      },
      {
        id: 804,
        name: "Stationery & Office Supplies",
        slug: "stationery-office-supplies",
        parentId: 8,
        children: [
          { id: 8041, name: "Notebooks & Diaries",   slug: "notebooks-diaries",  parentId: 804, children: [] },
          { id: 8042, name: "Pens & Pencils",        slug: "pens-pencils",       parentId: 804, children: [] },
          { id: 8043, name: "Highlighters & Markers",slug: "highlighters-markers",parentId: 804, children: [] },
          { id: 8044, name: "Sticky Notes",          slug: "sticky-notes",       parentId: 804, children: [] },
          { id: 8045, name: "Files & Folders",       slug: "files-folders",      parentId: 804, children: [] },
          { id: 8046, name: "Staplers & Punchers",   slug: "staplers-punchers",  parentId: 804, children: [] },
          { id: 8047, name: "Scissors & Cutters",    slug: "scissors-cutters",   parentId: 804, children: [] },
          { id: 8048, name: "Glue & Adhesives",      slug: "glue-adhesives",     parentId: 804, children: [] },
          { id: 8049, name: "Calculators",           slug: "calculators",        parentId: 804, children: [] },
          { id: 8050, name: "Desk Organisers",       slug: "desk-organisers",    parentId: 804, children: [] },
        ],
      },
      {
        id: 805,
        name: "Art & Craft Supplies",
        slug: "art-craft-supplies",
        parentId: 8,
        children: [
          { id: 8051, name: "Colour Pencils & Paints", slug: "colour-pencils-paints",  parentId: 805, children: [] },
          { id: 8052, name: "Sketch Books",            slug: "sketch-books",           parentId: 805, children: [] },
          { id: 8053, name: "Canvas & Easels",         slug: "canvas-easels",          parentId: 805, children: [] },
          { id: 8054, name: "Clay & Modelling Dough",  slug: "clay-modelling-dough",   parentId: 805, children: [] },
          { id: 8055, name: "Origami Paper",           slug: "origami-paper",          parentId: 805, children: [] },
          { id: 8056, name: "Calligraphy Sets",        slug: "calligraphy-sets",       parentId: 805, children: [] },
          { id: 8057, name: "Fabric & Sewing Kits",    slug: "fabric-sewing-kits",     parentId: 805, children: [] },
          { id: 8058, name: "Beads & Jewellery Making",slug: "beads-jewellery-making", parentId: 805, children: [] },
          { id: 8059, name: "Scrapbooking",            slug: "scrapbooking",           parentId: 805, children: [] },
          { id: 8060, name: "Drawing Tablets",         slug: "drawing-tablets",        parentId: 805, children: [] },
        ],
      },
    ],
  },
];  

export default navItems;